### ISSUE TITLE
Can't read config file in Amazon EC2 server

### ISSUE THREAD

**Issue by alexTheJumbo** [ilyakaznacheev/cleanenv#90] opened 2022-04-26 11:46 UTC
This is how I'm simply reading the config file:
```
func Read(path string) {
	readError := cleanenv.ReadConfig(path, &App)
	if readError != nil {
		log.Panic("Failed to read yaml file", readError)
	}
}
```
This is working on a my local machine (Mac) and in Docker container running locally.
But when I run the app on EC2 (built as RPM package and ran as a service), I get this error:
```
Process: 20421 ExecStart=/usr/bin/store-service -f /etc/store-service/config.yml (code=exited, status=2)
```
The very same code runs well when I parse the config using a library like `jessevdk/go-flags`. 
Any idea?

**Comment by ilyakaznacheev** [comment] 2022-08-18 09:28
Could you please investigate the case? I have no EC2 environment currently to do so.

**Comment by ehrktia** [comment] 2023-08-08 02:57
> This is how I'm simply reading the config file:
> 
> ```
> func Read(path string) {
> 	readError := cleanenv.ReadConfig(path, &App)
> 	if readError != nil {
> 		log.Panic("Failed to read yaml file", readError)
> 	}
> }
> ```
> 
> This is working on a my local machine (Mac) and in Docker container running locally. But when I run the app on EC2 (built as RPM package and ran as a service), I get this error:
> 
> ```
> Process: 20421 ExecStart=/usr/bin/store-service -f /etc/store-service/config.yml (code=exited, status=2)
> ```
> 
> The very same code runs well when I parse the config using a library like `jessevdk/go-flags`. Any idea?

@alexTheJumbo 
Can you please provide the complete trace associated with error message

**Comment by ilyakaznacheev** [comment] 2023-10-30 20:22
@ehrktia no idea tbh. Could you please try to collect logs?

**Comment by ilyakaznacheev** [comment] 2023-10-30 20:24
There doesn't seem to be much activity on this issue, perhaps the problem is no longer reproduced. I will close the issue until better times.

**Closed by ilyakaznacheev** 2023-10-30 20:24 UTC
Labels: help wanted
